services:
  spark-master:
    build:
      context: ..
      dockerfile: docker/Dockerfile.spark
    environment:
      - SPARK_MODE=master
      - SPARK_LOCAL_IP=spark-master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "7077:7077"
      - "9090:8080"
    volumes:
      - ../data:/opt/spark/data
      - ../src:/opt/spark/src
      - ../configs:/opt/spark/configs
    container_name: spark-master
    healthcheck:
      # Simplified health check that just verifies the process is running
      test: ["CMD-SHELL", "ps aux | grep org.apache.spark.deploy.master.Master | grep -v grep || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  spark-worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile.spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_WORKER_WEBUI_PORT=8081
    volumes:
      - ../data:/opt/spark/data
      - ../src:/opt/spark/src
      - ../configs:/opt/spark/configs
    depends_on:
      - spark-master
    deploy:
      replicas: 1

networks:
  default:
    name: spark-network
    driver: bridge